import { CharacterGender, CharacterStatus, Prisma } from '@prisma/client';

export const characterSeedData: Prisma.CharacterCreateInput[] = [
  {
    id: 'char_aurora_vale',
    image: 'https://i.pravatar.cc/512?u=aurora-vale',
    name: 'Aurora Vale',
    status: CharacterStatus.ALIVE,
    gender: CharacterGender.FEMALE,
    description: 'Orbital cartographer and rescue pilot known for mapping storm corridors.',
  },
  {
    id: 'char_bram_kestrel',
    image: 'https://i.pravatar.cc/512?u=bram-kestrel',
    name: 'Bram Kestrel',
    status: CharacterStatus.DEAD,
    gender: CharacterGender.MALE,
    description: 'Veteran engineer whose reactor notes still guide the fleet academy.',
  },
  {
    id: 'char_cyra_moon',
    image: 'https://i.pravatar.cc/512?u=cyra-moon',
    name: 'Cyra Moon',
    status: CharacterStatus.UNKNOWN,
    gender: CharacterGender.FEMALE,
    description: 'Archive detective last seen investigating a vanished desert observatory.',
  },
  {
    id: 'char_dax_renner',
    image: 'https://i.pravatar.cc/512?u=dax-renner',
    name: 'Dax Renner',
    status: CharacterStatus.ALIVE,
    gender: CharacterGender.MALE,
    description: 'Field medic with a dry wit and a habit of treating enemies first.',
  },
  {
    id: 'char_elian_fox',
    image: 'https://i.pravatar.cc/512?u=elian-fox',
    name: 'Elian Fox',
    status: CharacterStatus.UNKNOWN,
    gender: CharacterGender.UNKNOWN,
    description: 'Signal analyst whose encrypted music led scouts through the northern fog.',
  },
  {
    id: 'char_faye_morrow',
    image: 'https://i.pravatar.cc/512?u=faye-morrow',
    name: 'Faye Morrow',
    status: CharacterStatus.ALIVE,
    gender: CharacterGender.FEMALE,
    description: 'Botanist cultivating medicine gardens inside abandoned freight stations.',
  },
  {
    id: 'char_gideon_ash',
    image: 'https://i.pravatar.cc/512?u=gideon-ash',
    name: 'Gideon Ash',
    status: CharacterStatus.DEAD,
    gender: CharacterGender.MALE,
    description: 'Former city marshal remembered for solving the glass market murders.',
  },
  {
    id: 'char_hana_quill',
    image: 'https://i.pravatar.cc/512?u=hana-quill',
    name: 'Hana Quill',
    status: CharacterStatus.ALIVE,
    gender: CharacterGender.FEMALE,
    description: 'Diplomat and linguist who negotiates truces using old theatre scripts.',
  },
  {
    id: 'char_ion_trace',
    image: 'https://i.pravatar.cc/512?u=ion-trace',
    name: 'Ion Trace',
    status: CharacterStatus.UNKNOWN,
    gender: CharacterGender.MALE,
    description: 'Courier pilot rumored to cross borders through lightning fronts.',
  },
  {
    id: 'char_juno_starr',
    image: 'https://i.pravatar.cc/512?u=juno-starr',
    name: 'Juno Starr',
    status: CharacterStatus.DEAD,
    gender: CharacterGender.FEMALE,
    description: 'Stage illusionist whose final journal exposed a royal smuggling ring.',
  },
  {
    id: 'char_kael_warden',
    image: 'https://i.pravatar.cc/512?u=kael-warden',
    name: 'Kael Warden',
    status: CharacterStatus.ALIVE,
    gender: CharacterGender.MALE,
    description: 'Mountain ranger tracking missing expeditions near the black glacier.',
  },
  {
    id: 'char_lira_sable',
    image: 'https://i.pravatar.cc/512?u=lira-sable',
    name: 'Lira Sable',
    status: CharacterStatus.UNKNOWN,
    gender: CharacterGender.FEMALE,
    description: 'Undercover archivist preserving forbidden maps beneath the capital museum.',
  },
  {
    id: 'char_maren_void',
    image: 'https://i.pravatar.cc/512?u=maren-void',
    name: 'Maren Void',
    status: CharacterStatus.DEAD,
    gender: CharacterGender.UNKNOWN,
    description: 'Anonymous tactician credited with ending the nine-week bridge siege.',
  },
  {
    id: 'char_nadia_ember',
    image: 'https://i.pravatar.cc/512?u=nadia-ember',
    name: 'Nadia Ember',
    status: CharacterStatus.ALIVE,
    gender: CharacterGender.FEMALE,
    description: 'Fire rescue captain training volunteers in dense canal neighborhoods.',
  },
  {
    id: 'char_orren_pike',
    image: 'https://i.pravatar.cc/512?u=orren-pike',
    name: 'Orren Pike',
    status: CharacterStatus.DEAD,
    gender: CharacterGender.MALE,
    description: 'Submarine navigator whose logbook described a city below the ice shelf.',
  },
  {
    id: 'char_pax_riven',
    image: 'https://i.pravatar.cc/512?u=pax-riven',
    name: 'Pax Riven',
    status: CharacterStatus.UNKNOWN,
    gender: CharacterGender.UNKNOWN,
    description: 'Wandering mechanic linked to impossible repairs in three frontier towns.',
  },
  {
    id: 'char_quinn_rook',
    image: 'https://i.pravatar.cc/512?u=quinn-rook',
    name: 'Quinn Rook',
    status: CharacterStatus.ALIVE,
    gender: CharacterGender.UNKNOWN,
    description: 'Forensic accountant uncovering fraud across guild banks and trade houses.',
  },
  {
    id: 'char_rhea_nox',
    image: 'https://i.pravatar.cc/512?u=rhea-nox',
    name: 'Rhea Nox',
    status: CharacterStatus.DEAD,
    gender: CharacterGender.FEMALE,
    description: 'Night watch commander who held the eastern gate during the winter riot.',
  },
  {
    id: 'char_silas_crowe',
    image: 'https://i.pravatar.cc/512?u=silas-crowe',
    name: 'Silas Crowe',
    status: CharacterStatus.ALIVE,
    gender: CharacterGender.MALE,
    description: 'Street chef and informant with contacts in every port kitchen.',
  },
  {
    id: 'char_talia_bright',
    image: 'https://i.pravatar.cc/512?u=talia-bright',
    name: 'Talia Bright',
    status: CharacterStatus.UNKNOWN,
    gender: CharacterGender.FEMALE,
    description: 'Solar physicist decoding strange flares above the equatorial array.',
  },
  {
    id: 'char_uri_caldwell',
    image: 'https://i.pravatar.cc/512?u=uri-caldwell',
    name: 'Uri Caldwell',
    status: CharacterStatus.ALIVE,
    gender: CharacterGender.MALE,
    description: 'Public defender building a case file against corrupt magistrates.',
  },
  {
    id: 'char_vesper_lane',
    image: 'https://i.pravatar.cc/512?u=vesper-lane',
    name: 'Vesper Lane',
    status: CharacterStatus.DEAD,
    gender: CharacterGender.UNKNOWN,
    description: 'Radio host whose coded broadcasts helped civilians escape occupied zones.',
  },
  {
    id: 'char_willa_hart',
    image: 'https://i.pravatar.cc/512?u=willa-hart',
    name: 'Willa Hart',
    status: CharacterStatus.ALIVE,
    gender: CharacterGender.FEMALE,
    description: 'Trauma surgeon coordinating mobile clinics after the harbor quake.',
  },
  {
    id: 'char_xander_reed',
    image: 'https://i.pravatar.cc/512?u=xander-reed',
    name: 'Xander Reed',
    status: CharacterStatus.UNKNOWN,
    gender: CharacterGender.MALE,
    description: 'Antique bookseller suspected of hiding a living machine blueprint.',
  },
];
